/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // layerlens.ai design tokens — clean blue/gray professional palette
        'on-error-container': '#991B1B',
        'secondary-fixed-dim': '#86EFAC',
        'on-background': '#111827',
        'on-tertiary-fixed-variant': '#B91C1C',
        surface: '#F9FAFB',
        'error-container': '#FEE2E2',
        'on-primary-fixed-variant': '#1D4ED8',
        background: '#F9FAFB',
        'primary-container': '#DBEAFE',
        outline: '#9CA3AF',
        'tertiary-container': '#FEE2E2',
        'on-secondary-fixed': '#166534',
        error: '#DC2626',
        tertiary: '#991B1B',
        'surface-container-lowest': '#FFFFFF',
        'on-secondary-container': '#166534',
        'on-tertiary-container': '#DC2626',
        'tertiary-fixed': '#FEE2E2',
        'on-primary-container': '#1D4ED8',
        'surface-variant': '#DBEAFE',
        'on-surface-variant': '#6B7280',
        'primary-fixed': '#EFF6FF',
        'on-primary-fixed': '#1E3A8A',
        'on-tertiary': '#FFFFFF',
        'on-surface': '#111827',
        'on-secondary': '#FFFFFF',
        'outline-variant': '#E5E7EB',
        'inverse-on-surface': '#F9FAFB',
        'inverse-primary': '#93C5FD',
        'on-error': '#FFFFFF',
        'on-tertiary-fixed': '#7F1D1D',
        'surface-container-highest': '#D1D5DB',
        'on-primary': '#FFFFFF',
        'surface-bright': '#FFFFFF',
        primary: '#2563EB',
        'primary-fixed-dim': '#93C5FD',
        'surface-container-low': '#F9FAFB',
        'secondary-container': '#DCFCE7',
        secondary: '#16A34A',
        'surface-tint': '#2563EB',
        'secondary-fixed': '#BBF7D0',
        'tertiary-fixed-dim': '#FCA5A5',
        'surface-container': '#F3F4F6',
        'surface-container-high': '#E5E7EB',
        'on-secondary-fixed-variant': '#15803D',
        'surface-dim': '#D1D5DB',
        'inverse-surface': '#1F2937',
      },
      fontFamily: {
        headline: ['var(--font-inter)', 'Inter', 'sans-serif'],
        body: ['var(--font-inter)', 'Inter', 'sans-serif'],
        label: ['var(--font-inter)', 'Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
